name: Release Pages

on:
  # 手动触发
  workflow_dispatch:
  push:
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  release-page:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run docs:build

      - name: 更新doc
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        continue-on-error: true
        with:
          host: ${{ secrets.VPS_HOST }}
          user: ${{ secrets.VPS_USER }}
          pass: ${{ secrets.VPS_PASS }}
          port: ${{ secrets.VPS_PORT }}
          connect_timeout: 10s
          scp: |
            'src/.vuepress/dist/*' => /root/doc/
          last_ssh: |
            systemctl restart nginx