name: Release Pages

on:
  # 手动触发
  workflow_dispatch:
  push:
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  release-page:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: npm run docs:build

      - name: Zip dist directory
        run: |
          zip -r dist.zip src/.vuepress/dist/*
          mkdir -p dist
          mv dist.zip dist/

      - name: 更新doc
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        continue-on-error: true
        with:
          host: ${{ secrets.VPS_HOST }}
          user: ${{ secrets.VPS_USER }}
          pass: ${{ secrets.VPS_PASS }}
          port: ${{ secrets.VPS_PORT }}
          connect_timeout: 10s
          scp: |
            'dist/dist.zip' => /root/doc/
          last_ssh: |
            cd /root/doc
            unzip -o dist.zip
            rm dist.zip
            docker restart nginx
